// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/greper/ulogin/internal/dao/internal"
)

// internalAccessDao is an internal type for wrapping the internal DAO implementation.
type internalAccessDao = *internal.AccessDao

// accessDao is the data access object for the table access.
// You can define custom methods on it to extend its functionality as needed.
type accessDao struct {
	internalAccessDao
}

var (
	// Access is a globally accessible object for table access operations.
	Access = accessDao{
		internal.NewAccessDao(),
	}
)

// Add your custom methods and functionality below.
