// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/greper/ulogin/internal/dao/internal"
)

// internalOauthSettingDao is an internal type for wrapping the internal DAO implementation.
type internalOauthSettingDao = *internal.OauthSettingDao

// oauthSettingDao is the data access object for the table oauth_setting.
// You can define custom methods on it to extend its functionality as needed.
type oauthSettingDao struct {
	internalOauthSettingDao
}

var (
	// OauthSetting is a globally accessible object for table oauth_setting operations.
	OauthSetting = oauthSettingDao{
		internal.NewOauthSettingDao(),
	}
)

// Add your custom methods and functionality below.
