// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/greper/ulogin/internal/dao/internal"
)

// internalOauthBoundDao is an internal type for wrapping the internal DAO implementation.
type internalOauthBoundDao = *internal.OauthBoundDao

// oauthBoundDao is the data access object for the table oauth_bound.
// You can define custom methods on it to extend its functionality as needed.
type oauthBoundDao struct {
	internalOauthBoundDao
}

var (
	// OauthBound is a globally accessible object for table oauth_bound operations.
	OauthBound = oauthBoundDao{
		internal.NewOauthBoundDao(),
	}
)

// Add your custom methods and functionality below.
