// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/greper/ulogin/internal/dao/internal"
)

// internalSchemaMigrationsDao is an internal type for wrapping the internal DAO implementation.
type internalSchemaMigrationsDao = *internal.SchemaMigrationsDao

// schemaMigrationsDao is the data access object for the table schema_migrations.
// You can define custom methods on it to extend its functionality as needed.
type schemaMigrationsDao struct {
	internalSchemaMigrationsDao
}

var (
	// SchemaMigrations is a globally accessible object for table schema_migrations operations.
	SchemaMigrations = schemaMigrationsDao{
		internal.NewSchemaMigrationsDao(),
	}
)

// Add your custom methods and functionality below.
