// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/greper/ulogin/internal/dao/internal"
)

// internalSysSettingDao is an internal type for wrapping the internal DAO implementation.
type internalSysSettingDao = *internal.SysSettingDao

// sysSettingDao is the data access object for the table sys_setting.
// You can define custom methods on it to extend its functionality as needed.
type sysSettingDao struct {
	internalSysSettingDao
}

var (
	// SysSetting is a globally accessible object for table sys_setting operations.
	SysSetting = sysSettingDao{
		internal.NewSysSettingDao(),
	}
)

// Add your custom methods and functionality below.
