// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mine

import (
	"github.com/greper/ulogin/api/admin/mine"
)

type ControllerV1 struct{}

func NewV1() mine.IMineV1 {
	return &ControllerV1{}
}
